name: WordPress Plugin Unit test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  phpunit:
    name: WordPress ${{ matrix.wordpress }} * PHP v${{ matrix.php }} * ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-22.04 ]
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]
        wordpress: [ latest, nightly, '6.0' ]

    env:
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wordpress }}

    services:
      database:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP v${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, php-mysql

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install gettext library
        run: sudo apt-get install gettext

      - name: Update composer dependencies for lock file
        # Your lock file does not contain a compatible set of packages. Please run composer update.
        run: composer update

      - name: Install composer dependencies
        run: composer install

      - name: Install wp tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 0.0.0.0:3306 $WP_VERSION

      - name: Apply a patch
        run: cp tests/phpunit/patch/class-wp-block-supports.php /tmp/wordpress/wp-includes/class-wp-block-supports.php

      - name: Install Node.js package dependencies
        run: npm install

      - name: Build a plugin
        run: npm run build

      - name: Run PHPUnit - WordPress ${{ matrix.wordpress }}
        run: composer run phpunit

      - name: Run Jest unit test - WordPress ${{ matrix.wordpress }}
        run: npm run test:jest
        if: ${{ matrix.php == '8.2' && matrix.wordpress == 'latest' }}

      - name: Run PHP CodeSniffer - WordPress ${{ matrix.wordpress }}
        run: composer run phpcs
        if: ${{ matrix.php == '8.2' && matrix.wordpress == 'latest' }}
